// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNjziKNFzuI3MKziZD8F62Xpk640uHkvw',
    appId: '1:670526577063:web:cb9837658acb9760587e82',
    messagingSenderId: '670526577063',
    projectId: 'hotshot72',
    authDomain: 'hotshot72.firebaseapp.com',
    storageBucket: 'hotshot72.appspot.com',
    measurementId: 'G-E6LH0CQFJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbUTduMTNSZ9tIFuvxhDnkKN7FshQmJW8',
    appId: '1:670526577063:android:0cce38f22bc028d5587e82',
    messagingSenderId: '670526577063',
    projectId: 'hotshot72',
    storageBucket: 'hotshot72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvoIfnYibg24SmQ9pWD2UVdY0iynnMJ1A',
    appId: '1:670526577063:ios:5ce118ad14592d19587e82',
    messagingSenderId: '670526577063',
    projectId: 'hotshot72',
    storageBucket: 'hotshot72.appspot.com',
    iosClientId: '670526577063-of6gf8jq6tj9t13dbqnmhu0irvrph5up.apps.googleusercontent.com',
    iosBundleId: 'com.example.amitians',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvoIfnYibg24SmQ9pWD2UVdY0iynnMJ1A',
    appId: '1:670526577063:ios:5ce118ad14592d19587e82',
    messagingSenderId: '670526577063',
    projectId: 'hotshot72',
    storageBucket: 'hotshot72.appspot.com',
    iosClientId: '670526577063-of6gf8jq6tj9t13dbqnmhu0irvrph5up.apps.googleusercontent.com',
    iosBundleId: 'com.example.amitians',
  );
}
